/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardBuyerRouteImport } from './routes/dashboard/buyer'
import { Route as DashboardLogisticsRouteImport } from './routes/dashboard/logistics'
import { Route as DashboardSellerRouteImport } from './routes/dashboard/seller'
import { Route as DashboardWagesRouteImport } from './routes/dashboard/wages'
import { Route as ImpactIndexRouteImport } from './routes/impact/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as MarketplaceBulkLotsRouteImport } from './routes/marketplace/bulk-lots'
import { Route as DashboardMapIdRouteImport } from './routes/dashboard/map.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuyerRoute = DashboardBuyerRouteImport.update({
  id: '/dashboard/buyer',
  path: '/dashboard/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLogisticsRoute = DashboardLogisticsRouteImport.update({
  id: '/dashboard/logistics',
  path: '/dashboard/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSellerRoute = DashboardSellerRouteImport.update({
  id: '/dashboard/seller',
  path: '/dashboard/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWagesRoute = DashboardWagesRouteImport.update({
  id: '/dashboard/wages',
  path: '/dashboard/wages',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactIndexRoute = ImpactIndexRouteImport.update({
  id: '/impact/',
  path: '/impact/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceBulkLotsRoute = MarketplaceBulkLotsRouteImport.update({
  id: '/marketplace/bulk-lots',
  path: '/marketplace/bulk-lots',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMapIdRoute = DashboardMapIdRouteImport.update({
  id: '/dashboard/map/$id',
  path: '/dashboard/map/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/logistics': typeof DashboardLogisticsRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/dashboard/wages': typeof DashboardWagesRoute
  '/marketplace/bulk-lots': typeof MarketplaceBulkLotsRoute
  '/impact/': typeof ImpactIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/dashboard/map/$id': typeof DashboardMapIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/logistics': typeof DashboardLogisticsRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/dashboard/wages': typeof DashboardWagesRoute
  '/marketplace/bulk-lots': typeof MarketplaceBulkLotsRoute
  '/impact': typeof ImpactIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/dashboard/map/$id': typeof DashboardMapIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/buyer': typeof DashboardBuyerRoute
  '/dashboard/logistics': typeof DashboardLogisticsRoute
  '/dashboard/seller': typeof DashboardSellerRoute
  '/dashboard/wages': typeof DashboardWagesRoute
  '/marketplace/bulk-lots': typeof MarketplaceBulkLotsRoute
  '/impact/': typeof ImpactIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/dashboard/map/$id': typeof DashboardMapIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard/buyer'
    | '/dashboard/logistics'
    | '/dashboard/seller'
    | '/dashboard/wages'
    | '/marketplace/bulk-lots'
    | '/impact/'
    | '/marketplace/'
    | '/dashboard/map/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/buyer'
    | '/dashboard/logistics'
    | '/dashboard/seller'
    | '/dashboard/wages'
    | '/marketplace/bulk-lots'
    | '/impact'
    | '/marketplace'
    | '/dashboard/map/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard/buyer'
    | '/dashboard/logistics'
    | '/dashboard/seller'
    | '/dashboard/wages'
    | '/marketplace/bulk-lots'
    | '/impact/'
    | '/marketplace/'
    | '/dashboard/map/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardBuyerRoute: typeof DashboardBuyerRoute
  DashboardLogisticsRoute: typeof DashboardLogisticsRoute
  DashboardSellerRoute: typeof DashboardSellerRoute
  DashboardWagesRoute: typeof DashboardWagesRoute
  MarketplaceBulkLotsRoute: typeof MarketplaceBulkLotsRoute
  ImpactIndexRoute: typeof ImpactIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  DashboardMapIdRoute: typeof DashboardMapIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/buyer': {
      id: '/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof DashboardBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/logistics': {
      id: '/dashboard/logistics'
      path: '/dashboard/logistics'
      fullPath: '/dashboard/logistics'
      preLoaderRoute: typeof DashboardLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seller': {
      id: '/dashboard/seller'
      path: '/dashboard/seller'
      fullPath: '/dashboard/seller'
      preLoaderRoute: typeof DashboardSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wages': {
      id: '/dashboard/wages'
      path: '/dashboard/wages'
      fullPath: '/dashboard/wages'
      preLoaderRoute: typeof DashboardWagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact/': {
      id: '/impact/'
      path: '/impact'
      fullPath: '/impact/'
      preLoaderRoute: typeof ImpactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/bulk-lots': {
      id: '/marketplace/bulk-lots'
      path: '/marketplace/bulk-lots'
      fullPath: '/marketplace/bulk-lots'
      preLoaderRoute: typeof MarketplaceBulkLotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/map/$id': {
      id: '/dashboard/map/$id'
      path: '/dashboard/map/$id'
      fullPath: '/dashboard/map/$id'
      preLoaderRoute: typeof DashboardMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardBuyerRoute: DashboardBuyerRoute,
  DashboardLogisticsRoute: DashboardLogisticsRoute,
  DashboardSellerRoute: DashboardSellerRoute,
  DashboardWagesRoute: DashboardWagesRoute,
  MarketplaceBulkLotsRoute: MarketplaceBulkLotsRoute,
  ImpactIndexRoute: ImpactIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  DashboardMapIdRoute: DashboardMapIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
